### ISSUE TITLE
ERROR: Postprocessing: Conversion failed!

### ISSUE THREAD

**Issue by kelvin-keegen** [yt-dlp/FFmpeg-Builds#63]
Seems like there is a bug with this latest release. A re-download is required to merge the downloaded parts successfully

**Comment by bashonly** [comment]
Can you share a log? Steps to reproduce? It sounds like you're using yt-dlp, are you sure it's not a site/yt-dlp issue? Have you confirmed that it works with an older version?

**Comment by kelvin-keegen** [comment]
```
[debug] ffmpeg version N-116062-gcc6fb1643d-20240701 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 14.1.0 (crosstool-NG 1.26.0.93_a87bf7f)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-libxml2 --enable-openssl --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --enable-libdvdread --enable-libdvdnav --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs='-ldl -lgomp' --extra-ldflags=-pthread --extra-ldexeflags=-pie --cc=x86_64-ffbuild-linux-gnu-gcc --cxx=x86_64-ffbuild-linux-gnu-g++ --ar=x86_64-ffbuild-linux-gnu-gcc-ar --ranlib=x86_64-ffbuild-linux-gnu-gcc-ranlib --nm=x86_64-ffbuild-linux-gnu-gcc-nm --extra-version=20240701
  libavutil      59. 27.100 / 59. 27.100
  libavcodec     61.  9.100 / 61.  9.100
  libavformat    61.  4.100 / 61.  4.100
  libavdevice    61.  2.100 / 61.  2.100
  libavfilter    10.  2.102 / 10.  2.102
  libswscale      8.  2.100 /  8.  2.100
  libswresample   5.  2.100 /  5.  2.100
  libpostproc    58.  2.100 / 58.  2.100
Input #0, matroska,webm, from 'file:/app_data/downloads/ALPS & DOLOMITES (Drone + Timelapse) Heavenly Nature Relaxation™ 5 Minute Short Film in 4K UHD [7bOptq-NPJQ].f313.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:05:20.95, start: 0.000000, bitrate: 15388 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 3840x2160, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 1k tbn (default)
Input #1, matroska,webm, from 'file:/app_data/downloads/ALPS & DOLOMITES (Drone + Timelapse) Heavenly Nature Relaxation™ 5 Minute Short Film in 4K UHD [7bOptq-NPJQ].f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:05:20.98, start: -0.007000, bitrate: 126 kb/s
  Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Output #0, webm, to 'file:/app_data/downloads/ALPS & DOLOMITES (Drone + Timelapse) Heavenly Nature Relaxation™ 5 Minute Short Film in 4K UHD [7bOptq-NPJQ].temp.webm':
  Metadata:
    encoder         : Lavf61.4.100
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 3840x2160 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 1k tbn (default)
  Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Press [q] to stop, [?] for help
size=   48896KiB time=00:00:23.99 bitrate=16696.1kbits/s speed=  48x    
size=  102400KiB time=00:00:48.91 bitrate=17149.0kbits/s speed=48.9x    
size=  157440KiB time=00:01:14.80 bitrate=17240.8kbits/s speed=49.9x    
size=  197632KiB time=00:01:34.22 bitrate=17181.7kbits/s speed=47.1x    
size=  197632KiB time=00:01:34.79 bitrate=17079.2kbits/s speed=37.9x    
size=  197632KiB time=00:01:34.79 bitrate=17079.2kbits/s speed=31.6x    
size=  197632KiB time=00:01:34.79 bitrate=17079.2kbits/s speed=27.1x    
size=  212736KiB time=00:01:43.03 bitrate=16913.8kbits/s speed=25.8x    
size=  238592KiB time=00:01:57.45 bitrate=16641.5kbits/s speed=26.1x    
size=  262400KiB time=00:02:12.06 bitrate=16276.7kbits/s speed=26.4x    
size=  285184KiB time=00:02:25.81 bitrate=16022.2kbits/s speed=26.5x    
size=  303360KiB time=00:02:39.99 bitrate=15532.8kbits/s speed=26.7x    
size=  325632KiB time=00:02:53.87 bitrate=15342.1kbits/s speed=26.7x    
size=  346368KiB time=00:03:03.21 bitrate=15486.9kbits/s speed=26.2x    
size=  362496KiB time=00:03:09.85 bitrate=15641.2kbits/s speed=25.3x    
size=  387840KiB time=00:03:22.90 bitrate=15658.7kbits/s speed=25.4x    
size=  414208KiB time=00:03:35.01 bitrate=15781.3kbits/s speed=25.3x    
size=  439552KiB time=00:03:48.42 bitrate=15763.4kbits/s speed=25.4x    
size=  461824KiB time=00:03:59.90 bitrate=15769.8kbits/s speed=25.2x    
size=  483840KiB time=00:04:10.11 bitrate=15847.1kbits/s speed=  25x    
size=  497664KiB time=00:04:18.65 bitrate=15761.6kbits/s speed=24.6x    
size=  521984KiB time=00:04:33.87 bitrate=15613.4kbits/s speed=24.9x    
size=  548864KiB time=00:04:45.98 bitrate=15722.1kbits/s speed=24.9x    
size=  574464KiB time=00:05:03.80 bitrate=15490.3kbits/s speed=25.3x    
size=  604416KiB time=00:05:16.71 bitrate=15633.5kbits/s speed=25.3x    
[out#0/webm @ 0x5a2c04800740] Error closing file: Stale file handle
[out#0/webm @ 0x5a2c04800740] video:602826KiB audio:4852KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.030593%
size=  607864KiB time=00:05:20.95 bitrate=15515.1kbits/s speed=25.5x    
Conversion failed!

ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 3537, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 3719, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 3701, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 3679, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/postprocessor/common.py", line 23, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/postprocessor/common.py", line 128, in wrapper
    return func(self, info)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 839, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 329, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 367, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

```
Yesterday the same video downloaded without the Post processing error

**Comment by bashonly** [comment]
> Yesterday the same video downloaded without the Post processing error

Need to know what version it worked with

Also, what command are you running? Please share the FULL verbose log

**Comment by kelvin-keegen** [comment]
```
appuser@90aa57692c9f:/app_data$ yt-dlp -v --ffmpeg-location /app_data/dependencies/ffmpeg-master-latest-linux64-gpl/bin/ --path /app_data/downloads/ https://www.youtube.com/watch?v=7bOptq-NPJQ&pp=ygUMbmF0dXJlIDVtaW5z
[1] 416
appuser@90aa57692c9f:/app_data$ [debug] Command-line config: ['-v', '--ffmpeg-location', '/app_data/dependencies/ffmpeg-master-latest-linux64-gpl/bin/', '--path', '/app_data/downloads/', 'https://www.youtube.com/watch?v=7bOptq-NPJQ']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-41-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg N-116062-gcc6fb1643d-20240701 (setts), ffprobe N-116062-gcc6fb1643d-20240701
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=7bOptq-NPJQ
[youtube] 7bOptq-NPJQ: Downloading webpage
[youtube] 7bOptq-NPJQ: Downloading ios player API JSON
[debug] Loading youtube-nsig.81a0fcab from cache
[debug] [youtube] Decrypted nsig FWDQUjfXJhrLmymfxPcU => ikwv5v6SHqN6yQ
[debug] Loading youtube-nsig.81a0fcab from cache
[debug] [youtube] Decrypted nsig 5AhqEGBZ8zhZ1LQTks5V => 7OOzhmu46ibVXQ
[youtube] 7bOptq-NPJQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7bOptq-NPJQ: Downloading 1 format(s): 313+251
[debug] Invoking http downloader on "https://rr4---sn-2vgu0b5auxaxjvh-apnd.googlevideo.com/videoplayback?expire=1719890053&ei=JRyDZu78Har2mLAPvuaR-Ak&ip=144.64.155.128&id=o-ADzGewzyXsKa9bgf50glx_rZgaKH4sUcD8ig8hskweAd&itag=313&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=jV&mm=31%2C29&mn=sn-2vgu0b5auxaxjvh-apnd%2Csn-apn7en7s&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=24&initcwndbps=1410000&bui=AbKP-1Mb8ioIAns91CwRx-DIwrSpBcX-0BYg6ktIHTS_WgtSOzZkLylJFDpsjKUUGAEn8bG9VWpHxtIl&spc=NO7bAZfCtuIpOjDTD5NrI3meWE6FGOPn-3sPVWRlrbPtdCIWIvRA2U2Z7Bhj&vprv=1&svpuc=1&mime=video%2Fwebm&ns=O16kwIUBLYyma7VqmCs3IO4Q&rqh=1&gir=yes&clen=617370263&dur=320.954&lmt=1708681979683773&mt=1719867669&fvip=4&keepalive=yes&c=WEB&sefc=1&txp=4532434&n=7OOzhmu46ibVXQ&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAITVmx57Ie5KW8FLdwKnyo4EjkTaQg0T84NVwxiOwvfPAiB0KINmYcZ9TMBavPO8LZT0WGvdVa-9LRC4_t0JfEx0Fg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIhAPUq_BTa9OAejH1YhsMVVLd-eBYkkDx6SqUu2UJUq9GFAiBYljKxBAIT4bfrUCBhq9nZ-5LSxgAgErLflYVGI99ILw%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: /app_data/downloads/ALPS & DOLOMITES (Drone + Timelapse) Heavenly Nature Relaxation™ 5 Minute Short Film in 4K UHD [7bOptq-NPJQ].f313.webm
[download] 100% of  588.77MiB in 00:01:17 at 7.58MiB/s
[debug] Invoking http downloader on "https://rr4---sn-2vgu0b5auxaxjvh-apnd.googlevideo.com/videoplayback?expire=1719890053&ei=JRyDZu78Har2mLAPvuaR-Ak&ip=144.64.155.128&id=o-ADzGewzyXsKa9bgf50glx_rZgaKH4sUcD8ig8hskweAd&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=jV&mm=31%2C29&mn=sn-2vgu0b5auxaxjvh-apnd%2Csn-apn7en7s&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=24&initcwndbps=1410000&bui=AbKP-1Mb8ioIAns91CwRx-DIwrSpBcX-0BYg6ktIHTS_WgtSOzZkLylJFDpsjKUUGAEn8bG9VWpHxtIl&spc=NO7bAZfCtuIpOjDTD5NrI3meWE6FGOPn-3sPVWRlrbPtdCIWIvRA2U2Z7Bhj&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=O16kwIUBLYyma7VqmCs3IO4Q&rqh=1&gir=yes&clen=5081750&dur=320.981&lmt=1708676980122763&mt=1719867669&fvip=4&keepalive=yes&c=WEB&sefc=1&txp=4532434&n=7OOzhmu46ibVXQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgVqcAkkHhl_o0tvNCPSg2rAhFd43QqzRLxm9bV3Sjm4MCIQDmDWC5fniXvj9jsEioTJB22ffsXAGvP_KTKRyKriKNrA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIhAPUq_BTa9OAejH1YhsMVVLd-eBYkkDx6SqUu2UJUq9GFAiBYljKxBAIT4bfrUCBhq9nZ-5LSxgAgErLflYVGI99ILw%3D%3D"
[download] Destination: /app_data/downloads/ALPS & DOLOMITES (Drone + Timelapse) Heavenly Nature Relaxation™ 5 Minute Short Film in 4K UHD [7bOptq-NPJQ].f251.webm
[download] 100% of    4.85MiB in 00:00:01 at 3.08MiB/s
[Merger] Merging formats into "/app_data/downloads/ALPS & DOLOMITES (Drone + Timelapse) Heavenly Nature Relaxation™ 5 Minute Short Film in 4K UHD [7bOptq-NPJQ].webm"
[debug] ffmpeg command line: /app_data/dependencies/ffmpeg-master-latest-linux64-gpl/bin/ffmpeg -y -loglevel repeat+info -i 'file:/app_data/downloads/ALPS & DOLOMITES (Drone + Timelapse) Heavenly Nature Relaxation™ 5 Minute Short Film in 4K UHD [7bOptq-NPJQ].f313.webm' -i 'file:/app_data/downloads/ALPS & DOLOMITES (Drone + Timelapse) Heavenly Nature Relaxation™ 5 Minute Short Film in 4K UHD [7bOptq-NPJQ].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:/app_data/downloads/ALPS & DOLOMITES (Drone + Timelapse) Heavenly Nature Relaxation™ 5 Minute Short Film in 4K UHD [7bOptq-NPJQ].temp.webm'
[debug] ffmpeg version N-116062-gcc6fb1643d-20240701 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 14.1.0 (crosstool-NG 1.26.0.93_a87bf7f)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-libxml2 --enable-openssl --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --enable-libdvdread --enable-libdvdnav --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs='-ldl -lgomp' --extra-ldflags=-pthread --extra-ldexeflags=-pie --cc=x86_64-ffbuild-linux-gnu-gcc --cxx=x86_64-ffbuild-linux-gnu-g++ --ar=x86_64-ffbuild-linux-gnu-gcc-ar --ranlib=x86_64-ffbuild-linux-gnu-gcc-ranlib --nm=x86_64-ffbuild-linux-gnu-gcc-nm --extra-version=20240701
  libavutil      59. 27.100 / 59. 27.100
  libavcodec     61.  9.100 / 61.  9.100
  libavformat    61.  4.100 / 61.  4.100
  libavdevice    61.  2.100 / 61.  2.100
  libavfilter    10.  2.102 / 10.  2.102
  libswscale      8.  2.100 /  8.  2.100
  libswresample   5.  2.100 /  5.  2.100
  libpostproc    58.  2.100 / 58.  2.100
Input #0, matroska,webm, from 'file:/app_data/downloads/ALPS & DOLOMITES (Drone + Timelapse) Heavenly Nature Relaxation™ 5 Minute Short Film in 4K UHD [7bOptq-NPJQ].f313.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:05:20.95, start: 0.000000, bitrate: 15388 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 3840x2160, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 1k tbn (default)
Input #1, matroska,webm, from 'file:/app_data/downloads/ALPS & DOLOMITES (Drone + Timelapse) Heavenly Nature Relaxation™ 5 Minute Short Film in 4K UHD [7bOptq-NPJQ].f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:05:20.98, start: -0.007000, bitrate: 126 kb/s
  Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Output #0, webm, to 'file:/app_data/downloads/ALPS & DOLOMITES (Drone + Timelapse) Heavenly Nature Relaxation™ 5 Minute Short Film in 4K UHD [7bOptq-NPJQ].temp.webm':
  Metadata:
    encoder         : Lavf61.4.100
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 3840x2160 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 1k tbn (default)
  Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Press [q] to stop, [?] for help
size=   48896KiB time=00:00:23.99 bitrate=16696.1kbits/s speed=  48x    
size=  102400KiB time=00:00:48.91 bitrate=17149.0kbits/s speed=48.9x    
size=  157440KiB time=00:01:14.80 bitrate=17240.8kbits/s speed=49.9x    
size=  197632KiB time=00:01:34.22 bitrate=17181.7kbits/s speed=47.1x    
size=  197632KiB time=00:01:34.79 bitrate=17079.2kbits/s speed=37.9x    
size=  197632KiB time=00:01:34.79 bitrate=17079.2kbits/s speed=31.6x    
size=  197632KiB time=00:01:34.79 bitrate=17079.2kbits/s speed=27.1x    
size=  212736KiB time=00:01:43.03 bitrate=16913.8kbits/s speed=25.8x    
size=  238592KiB time=00:01:57.45 bitrate=16641.5kbits/s speed=26.1x    
size=  262400KiB time=00:02:12.06 bitrate=16276.7kbits/s speed=26.4x    
size=  285184KiB time=00:02:25.81 bitrate=16022.2kbits/s speed=26.5x    
size=  303360KiB time=00:02:39.99 bitrate=15532.8kbits/s speed=26.7x    
size=  325632KiB time=00:02:53.87 bitrate=15342.1kbits/s speed=26.7x    
size=  346368KiB time=00:03:03.21 bitrate=15486.9kbits/s speed=26.2x    
size=  362496KiB time=00:03:09.85 bitrate=15641.2kbits/s speed=25.3x    
size=  387840KiB time=00:03:22.90 bitrate=15658.7kbits/s speed=25.4x    
size=  414208KiB time=00:03:35.01 bitrate=15781.3kbits/s speed=25.3x    
size=  439552KiB time=00:03:48.42 bitrate=15763.4kbits/s speed=25.4x    
size=  461824KiB time=00:03:59.90 bitrate=15769.8kbits/s speed=25.2x    
size=  483840KiB time=00:04:10.11 bitrate=15847.1kbits/s speed=  25x    
size=  497664KiB time=00:04:18.65 bitrate=15761.6kbits/s speed=24.6x    
size=  521984KiB time=00:04:33.87 bitrate=15613.4kbits/s speed=24.9x    
size=  548864KiB time=00:04:45.98 bitrate=15722.1kbits/s speed=24.9x    
size=  574464KiB time=00:05:03.80 bitrate=15490.3kbits/s speed=25.3x    
size=  604416KiB time=00:05:16.71 bitrate=15633.5kbits/s speed=25.3x    
[out#0/webm @ 0x5a2c04800740] Error closing file: Stale file handle
[out#0/webm @ 0x5a2c04800740] video:602826KiB audio:4852KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.030593%
size=  607864KiB time=00:05:20.95 bitrate=15515.1kbits/s speed=25.5x    
Conversion failed!

ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 3537, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 3719, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 3701, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 3679, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/postprocessor/common.py", line 23, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/postprocessor/common.py", line 128, in wrapper
    return func(self, info)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 839, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 329, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 367, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!


```
yt-dlp version
```
appuser@90aa57692c9f:/app_data$ yt-dlp --version
2024.05.27
```

**Comment by bashonly** [comment]
is `/app_data` a NFS mount?

**Comment by kelvin-keegen** [comment]
yeah, it´s an NFS mount

**Comment by nihil-admirari** [comment]
Does the error reproduce with the upstream https://github.com/BtbN/FFmpeg-Builds FFmpeg and on a local filesystem?

**Comment by kelvin-keegen** [comment]
Seems like on a local system its working great. Both the upstream and the yt-dlp ffmpeg build

**Comment by nihil-admirari** [comment]
Does the upstream fail on NFS?

**Comment by kelvin-keegen** [comment]
Hey guys! So i did some extensive testing and it seems like its an NFS permission issue. since the locations of the ffmpeg and the downloaded content where in different locations seems like there was some generic errors getting triggered.
